
import java.util.Arrays;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class TebakNamaWindows extends javax.swing.JFrame {
    String namaNama[] = {"Mayu Watanabe","Emma Watson","Bonnie Wright","Emma Stone","Evana Lynch","Oliver Phelp",
                             "James Phelp", "Michael Jackson"};
    String nama = null;
    int maxTry=3;

    /**
     * Creates new form TebakNamaWindows
     */
    public TebakNamaWindows() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        mulaiButton = new javax.swing.JButton();
        mulaiLabel = new javax.swing.JLabel();
        inputNamaTextField = new javax.swing.JTextField();
        cekNamaButton = new javax.swing.JButton();
        clueLabel = new javax.swing.JLabel();
        inputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\unnamed.jpg")); // NOI18N

        mulaiButton.setText("Mulai");
        mulaiButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mulaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiButtonActionPerformed(evt);
            }
        });

        mulaiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mulaiLabel.setText("Klik Mulai !!");

        inputNamaTextField.setEnabled(false);

        cekNamaButton.setText("Yakin ?");
        cekNamaButton.setEnabled(false);
        cekNamaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekNamaButtonActionPerformed(evt);
            }
        });

        clueLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        clueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clueLabel.setText("???");

        inputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputLabel.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mulaiLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mulaiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cekNamaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputNamaTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(mulaiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mulaiButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNamaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cekNamaButton)
                .addGap(21, 21, 21))
        );

        setSize(new java.awt.Dimension(396, 364));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiButtonActionPerformed
        // TODO add your handling code here:
        nama = namaNama[generateNama()].toUpperCase();
        char[] huruf = nama.toCharArray();
        Arrays.sort(huruf);
        String huruf1 = String.valueOf(huruf);
        mulaiButton.setEnabled(false);
        mulaiLabel.setText(" ");
        clueLabel.setText(huruf1);
        inputLabel.setText("Masukkan Jawaban Dari Clue DiAtas");
        inputNamaTextField.setEnabled(true);
        cekNamaButton.setEnabled(true);
    }//GEN-LAST:event_mulaiButtonActionPerformed

    private void cekNamaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekNamaButtonActionPerformed
        // TODO add your handling code here:
        String jawaban = inputNamaTextField.getText();
        
        if (nama.equalsIgnoreCase(jawaban)){
            inputLabel.setText("Jawaban = " + nama +" !! Benar, Selamat Anda Berhasil !!");
            inputNamaTextField.setEnabled(false);
            cekNamaButton.setEnabled(false);
            mulaiButton.setEnabled(true);
            mulaiLabel.setText("Klik Mulai Lagi !!");
            inputNamaTextField.setText("");
            
        }
        else{
            inputLabel.setText("Salah, Silahkan Jawab Lagi !!");
            inputNamaTextField.setText("");
            maxTry--;
            if (maxTry==0){
                inputLabel.setText("Anda Gagal, Jawaban Yang Benar Adalah: "+ nama);
                inputNamaTextField.setEnabled(false);
                cekNamaButton.setEnabled(false);
                mulaiButton.setEnabled(true);
                mulaiLabel.setText("Klik Mulai Lagi !!");
                inputNamaTextField.setText("");
            }
        }
    }//GEN-LAST:event_cekNamaButtonActionPerformed

    private int generateNama(){
        double random = Math.random()*10;
        double floor = Math.floor(random);
        int namaAcak = (int) floor;
        return namaAcak;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakNamaWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakNamaWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakNamaWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakNamaWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakNamaWindows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekNamaButton;
    private javax.swing.JLabel clueLabel;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JTextField inputNamaTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mulaiButton;
    private javax.swing.JLabel mulaiLabel;
    // End of variables declaration//GEN-END:variables
}
